dashboard:
  title: CentOS
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/centos.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Tempest Devstack Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-platform-centos7-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-platform-centos7-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-platform-centos7-nv')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Periodic AFS packaging (Periodic queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-package-afs-centos7.FAILURE),sum(stats_counts.zuul.pipeline.priodic.job.periodic-package-afs-centos7.{SUCCESS,FAILURE})),'24hours'), 'periodic-package-afs-centos7')
          type: graph
