dashboard:
  title: Fedora
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/fedora.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Tempest Devstack Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-platform-fedora23-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-platform-fedora23-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-platform-fedora23-nv')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Infra-puppet-apply Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-infra-puppet-apply-fedora-23.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-infra-puppet-apply-fedora-23.{SUCCESS,FAILURE})),'24hours'), 'gate-infra-puppet-apply-fedora-23')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Infra-puppet-apply Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-infra-puppet-apply-fedora-23.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-infra-puppet-apply-fedora-23.{SUCCESS,FAILURE})),'24hours'), 'gate-infra-puppet-apply-fedora-23')
          type: graph
