dashboard:
  title: Networking OVN Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/networking-ovn.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rate (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python27.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python27.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python27')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rate (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python27.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python27.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python27')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Integrated Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-ovn')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn-native-l3.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn-native-l3.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-ovn-native-l3')
          type: graph
