dashboard:
  title: Zuul Status
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/zuul-status.yaml).
          type: text
    - title: Single Stats
      height: 150px
      panels:
        - title: Check Pipeline
          span: 4
          sparkline:
            full: true
            show: true
          targets:
            - target: stats.gauges.zuul.pipeline.check.current_changes
          type: singlestat
        - title: Gate Pipeline
          span: 4
          sparkline:
            full: true
            show: true
          targets:
            - target: stats.gauges.zuul.pipeline.gate.current_changes
          type: singlestat
        - title: Post Pipeline
          span: 4
          sparkline:
            full: true
            show: true
          targets:
            - target: stats.gauges.zuul.pipeline.post.current_changes
          type: singlestat
    - title: Graphs
      height: 250px
      panels:
        - title: Test Nodes
          span: 4
          stack: true
          targets:
            - target: alias(stats.gauges.nodepool.target.building, 'Building')
            - target: alias(stats.gauges.nodepool.target.ready, 'Available')
            - target: alias(stats.gauges.nodepool.target.used, 'In Use')
            - target: alias(stats.gauges.nodepool.target.delete, 'Deleting')
          type: graph
        - title: Zuul Jobs Launched (per Hour)
          span: 4
          targets:
            - target: alias(summarize(sumSeries(stats_counts.zuul.pipeline.*.all_jobs), '1h'), 'All Jobs')
          type: graph
        - title: Gerrit Events (per Hour)
          span: 4
          targets:
            - target: alias(summarize(stats_counts.gerrit.event.comment-added, '1h'), 'Comment added')
            - target: alias(summarize(stats_counts.gerrit.event.patchset-created, '1h'), 'Patchset created')
            - target: alias(summarize(stats_counts.gerrit.event.change-merged, '1h'), 'Change merged')
          type: graph
        - title: Zuul Job Queue
          span: 4
          targets:
            - target: alias(stats.gauges.zuul.geard.queue.running, 'Running')
            - target: alias(stats.gauges.zuul.geard.queue.waiting, 'Waiting')
            - target: alias(stats.gauges.zuul.geard.queue.total, 'Total Jobs')
            - target: alias(stats.gauges.zuul.geard.workers, 'Workers')
          type: graph
        - title: Logstash Job Queue
          span: 4
          targets:
            - target: alias(stats.gauges.logstash.geard.queue.running, 'Running')
            - target: alias(stats.gauges.logstash.geard.queue.waiting, 'Waiting')
            - target: alias(stats.gauges.logstash.geard.queue.total, 'Total Jobs')
            - target: alias(stats.gauges.logstash.geard.workers, 'Workers')
          type: graph
